# BEGIN_KITTY_THEME
include theme.conf
# END_KITTY_THEME

# Optik & Transparenz
hide_window_decorations yes
window_padding_width 12
background_opacity 0.85

# Schrift & Ligaturen (Schriftname ggf. anpassen)
font_family ttf-ibmplex-mono-nerd Nerd Font
disable_ligatures never