# === UI & Background ===
background #050209
foreground #c4ede9

# === Cursor & Selection ===
cursor #e41148
cursor_text_color #050209
selection_background #ffd23f
selection_foreground #050209

# === Window Borders ===
active_border_color #c4ede9
inactive_border_color #595c61

# === Terminal Colors (ANSI) ===
color0  #050209
color1  #c9032f
color2  #595c61
color3  #ffd23f
color4  #c4ede9
color5  #e41148
color6  #595c61
color7  #c4ede9
color8  #595c61
color9  #e41148
color10 #ffd23f
color11 #ffd23f
color12 #c4ede9
color13 #e41148
color14 #c9032f
color15 #c4ede9