# === UI & Background ===
background #050209
foreground #c4ede9

# === Cursor & Selection ===
cursor #e41148
cursor_text_color #050209
selection_background #ffd23f
selection_foreground #050209

# === Window Borders ===
active_border_color #00ff66
inactive_border_color #595c61

# === Terminal Colors (ANSI) ===
color0  #191711
color1  #a50707
color2  #a59f07
color3  #0aa507
color4  #07a5a5
color5  #070da5
color6  #a207a5
color7  #bfbcb4
color8  #3f3a2d
color9  #d80909
color10 #d8d009
color11 #0dd809
color12 #09d8d8
color13 #0911d8
color14 #d409d8
color15 #f2f0eb